# render.yaml
# Instructions for the Render platform to build and deploy the service.

services:
  # A web service
  - type: web
    name: llm-logic-service
    # Environment: Python 3.11
    env: python
    # Every time you push, Render will automatically deploy the new version.
    autoDeploy: true
    # The build and start commands for our service
    buildCommand: "pip install -r requirements.txt"
    # CORRECTED START COMMAND: Points to the 'app' variable in the 'main.py' file.
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    # Define where to find the secret .env file
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - fromGroup: llm-secrets
